@baseUrl = http://localhost:3001
@token = Bearer TOKENNI_SHU_YERGA_QOYING
@departmentId = 1


### Login - javobdan tokenni yuqoridagi @token ga qo'ying
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "muhammad",
  "password": "12345678"
}


### Bo'limlar ro'yxati
GET {{baseUrl}}/departments?q=&is_active=true&offset=0&limit=20&sort_by=sort_order&sort_order=asc
Authorization: {{token}}


### Bitta bo'lim
GET {{baseUrl}}/departments/{{departmentId}}
Authorization: {{token}}


### Bo'lim yaratish (super_admin/admin)
POST {{baseUrl}}/departments
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Bo'yoq",
  "code": "boyoq",
  "description": "Mahsulot bo'yash bo'limi",
  "sort_order": 5,
  "is_active": true
}


### Bo'limni tahrirlash (super_admin/admin)
PATCH {{baseUrl}}/departments/{{departmentId}}
Authorization: {{token}}
Content-Type: application/json

{
  "description": "Mahsulotni kesish va bichish",
  "sort_order": 1,
  "is_active": true
}


### Bo'limni o'chirish (super_admin/admin)
DELETE {{baseUrl}}/departments/{{departmentId}}
Authorization: {{token}}
