const router = require("express").Router();
const { isLoggedIn, hasRole } = require("../../shared/auth");
const c = require("./_controllers");
const manager = [isLoggedIn, hasRole("super_admin", "admin")];
router.get("/payroll-periods", ...manager, c.listPayroll);
router.get("/payroll-periods/:id", ...manager, c.showPayroll);
router.post("/payroll-periods", ...manager, c.createPayroll);
router.patch("/payroll-lines/:id", ...manager, c.updatePayrollLine);
router.post("/payroll-periods/:id/close", ...manager, c.closePayroll);
router.get("/expense-categories", ...manager, c.listCategories);
router.post("/expense-categories", ...manager, c.createCategory);
router.get("/expenses", ...manager, c.listExpenses);
router.post("/expenses", ...manager, c.createExpense);
router.get("/financial-accounts", ...manager, c.listAccounts);
router.post("/financial-accounts", ...manager, c.createAccount);
router.get("/cash-transactions", ...manager, c.listTransactions);
router.post("/cash-transactions", ...manager, c.createTransaction);
router.get("/client-returns", ...manager, c.listReturns);
router.post("/client-returns", ...manager, c.createReturn);
router.get("/reports/profit-loss", ...manager, c.profitLoss);
module.exports = router;
