const router = require("express").Router();
const c = require("./_controllers");
const isPlatformAdmin = require("../../shared/auth/is-platform-admin");
router.post("/login", c.login);
router.get("/companies", isPlatformAdmin, c.listCompanies);
router.post("/companies", isPlatformAdmin, c.createCompany);
router.patch("/companies/:id", isPlatformAdmin, c.updateCompany);
router.get("/payments", isPlatformAdmin, c.listPayments);
router.post("/payments", isPlatformAdmin, c.createPayment);
module.exports = router;
